[2025-04-09T16:11:33.362+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T16:11:33.381+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted manual__2025-04-09T16:11:06+00:00 [queued]>
[2025-04-09T16:11:33.390+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted manual__2025-04-09T16:11:06+00:00 [queued]>
[2025-04-09T16:11:33.391+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-09T16:11:33.524+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_trusted> on 2025-04-09 16:11:06+00:00
[2025-04-09T16:11:33.529+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1002) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T16:11:33.531+0000] {standard_task_runner.py:72} INFO - Started process 1004 to run task
[2025-04-09T16:11:33.532+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'run_dbt_trusted', 'manual__2025-04-09T16:11:06+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/driven_data_pipeline.py', '--cfg-path', '/tmp/tmpjqzpt9b9']
[2025-04-09T16:11:33.533+0000] {standard_task_runner.py:105} INFO - Job 92: Subtask run_dbt_trusted
[2025-04-09T16:11:33.612+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.run_dbt_trusted manual__2025-04-09T16:11:06+00:00 [running]> on host 5a8aeda502d0
[2025-04-09T16:11:33.760+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_trusted' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T16:11:06+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T16:11:06+00:00'
[2025-04-09T16:11:33.762+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-09T16:11:33.779+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T16:11:33.780+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'set -x; cd /opt/***/dbt && dbt run --select tag:trusted']
[2025-04-09T16:11:33.791+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T16:11:33.793+0000] {subprocess.py:93} INFO - + cd /opt/***/dbt
[2025-04-09T16:11:33.793+0000] {subprocess.py:93} INFO - + dbt run --select tag:trusted
[2025-04-09T16:11:36.534+0000] {subprocess.py:93} INFO - [0m16:11:36  Running with dbt=1.8.0
[2025-04-09T16:11:36.855+0000] {subprocess.py:93} INFO - [0m16:11:36  Registered adapter: postgres=1.8.2
[2025-04-09T16:11:37.399+0000] {subprocess.py:93} INFO - [0m16:11:37  Found 9 models, 10 sources, 428 macros
[2025-04-09T16:11:37.404+0000] {subprocess.py:93} INFO - [0m16:11:37
[2025-04-09T16:11:37.575+0000] {subprocess.py:93} INFO - [0m16:11:37  Concurrency: 1 threads (target='dev')
[2025-04-09T16:11:37.576+0000] {subprocess.py:93} INFO - [0m16:11:37
[2025-04-09T16:11:37.589+0000] {subprocess.py:93} INFO - [0m16:11:37  1 of 4 START sql table model driven_trusted.non_pii_data ....................... [RUN]
[2025-04-09T16:11:44.000+0000] {subprocess.py:93} INFO - [0m16:11:43  1 of 4 OK created sql table model driven_trusted.non_pii_data .................. [[32mSELECT 144391[0m in 6.41s]
[2025-04-09T16:11:44.003+0000] {subprocess.py:93} INFO - [0m16:11:44  2 of 4 START sql table model driven_trusted.payment_data ....................... [RUN]
[2025-04-09T16:11:46.545+0000] {subprocess.py:93} INFO - [0m16:11:46  2 of 4 OK created sql table model driven_trusted.payment_data .................. [[32mSELECT 144391[0m in 2.54s]
[2025-04-09T16:11:46.551+0000] {subprocess.py:93} INFO - [0m16:11:46  3 of 4 START sql table model driven_trusted.pii_data ........................... [RUN]
[2025-04-09T16:11:52.662+0000] {subprocess.py:93} INFO - [0m16:11:52  3 of 4 OK created sql table model driven_trusted.pii_data ...................... [[32mSELECT 144391[0m in 6.11s]
[2025-04-09T16:11:52.680+0000] {subprocess.py:93} INFO - [0m16:11:52  4 of 4 START sql table model driven_trusted.technical_data ..................... [RUN]
[2025-04-09T16:11:56.125+0000] {subprocess.py:93} INFO - [0m16:11:56  4 of 4 OK created sql table model driven_trusted.technical_data ................ [[32mSELECT 144391[0m in 3.45s]
[2025-04-09T16:11:56.161+0000] {subprocess.py:93} INFO - [0m16:11:56
[2025-04-09T16:11:56.167+0000] {subprocess.py:93} INFO - [0m16:11:56  Finished running 4 table models in 0 hours 0 minutes and 18.75 seconds (18.75s).
[2025-04-09T16:11:56.382+0000] {subprocess.py:93} INFO - [0m16:11:56
[2025-04-09T16:11:56.384+0000] {subprocess.py:93} INFO - [0m16:11:56  [32mCompleted successfully[0m
[2025-04-09T16:11:56.386+0000] {subprocess.py:93} INFO - [0m16:11:56
[2025-04-09T16:11:56.387+0000] {subprocess.py:93} INFO - [0m16:11:56  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 TOTAL=4
[2025-04-09T16:11:57.481+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-09T16:11:57.717+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-09T16:11:57.719+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_raw_data_pipeline, task_id=run_dbt_trusted, run_id=manual__2025-04-09T16:11:06+00:00, execution_date=20250409T161106, start_date=20250409T161133, end_date=20250409T161157
[2025-04-09T16:11:57.889+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-09T16:11:57.947+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T16:11:57.974+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
